// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAjadVANeVf2bxyk1N_5YFW1xnTBMHtE',
    appId: '1:155091884903:web:0e794f166e288632972dc2',
    messagingSenderId: '155091884903',
    projectId: 'chatapp-1546b',
    authDomain: 'chatapp-1546b.firebaseapp.com',
    storageBucket: 'chatapp-1546b.firebasestorage.app',
    measurementId: 'G-DE8GL6K5RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNuOU0_MML1KnGO_I5olUIMd_j1sVf3Ao',
    appId: '1:155091884903:android:0717a40666063676972dc2',
    messagingSenderId: '155091884903',
    projectId: 'chatapp-1546b',
    storageBucket: 'chatapp-1546b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAJTl4gm0d4TOD5SBGCW5waSslo1a8yY',
    appId: '1:155091884903:ios:7847d8847153fec9972dc2',
    messagingSenderId: '155091884903',
    projectId: 'chatapp-1546b',
    storageBucket: 'chatapp-1546b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPAJTl4gm0d4TOD5SBGCW5waSslo1a8yY',
    appId: '1:155091884903:ios:7847d8847153fec9972dc2',
    messagingSenderId: '155091884903',
    projectId: 'chatapp-1546b',
    storageBucket: 'chatapp-1546b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAjadVANeVf2bxyk1N_5YFW1xnTBMHtE',
    appId: '1:155091884903:web:3d2035c013ac0473972dc2',
    messagingSenderId: '155091884903',
    projectId: 'chatapp-1546b',
    authDomain: 'chatapp-1546b.firebaseapp.com',
    storageBucket: 'chatapp-1546b.firebasestorage.app',
    measurementId: 'G-ZR6EYHZ8HE',
  );
}
